spring:
  ngrokUrl: https://058c-223-178-80-6.ngrok-free.app
  cloud:
    aws:
      s3:
        endpoint: http://localhost:4566
        bucket: local
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect  # Use MySQL8Dialect for MySQL 8+
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/socialeaze
    username: root
    password: JaGaMaRA1706
    driver-class-name: com.mysql.cj.jdbc.Driver  # Fixed the driver class name
    hikari:
      maximum-pool-size: 5
  application:
    name: api
app:
  cors:
    allowedOrigins:
      - "https://*.stackblitz.io"
      - "http://localhost:3000"
      - "*.webcontainer-api.io"
      - "https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-ommlfhg8--3000--495c5120.local-credentialless.webcontainer-api.io"
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
channel:
  linkedin:
    clientid: 86gu36q9t2wcg1
    clientsecret: WPL_AP1.jsYQG4hqKtMvQHKb.EmxZug==
    redirecturi: http://localhost:3000/callback/linkedin
    scope: openid,w_member_social,profile,email
  twitter:
    clientid: RlF6OWxxSXNmQ2RJRjczYndwNkY6MTpjaQ
    clientsecret: xu_7MZm41No0CrddMr0905Jh6hlFdC-P1-PnUWfVl6UHxk48Xl
    redirecturi: http://localhost:3000/callback/twitter
    scope: tweet.read tweet.write offline.access users.read
  instagram:
    clientid: 1697823837436999
    clientsecret: 9d85d01d76e12b0cf00b3e0744051bb9
    redirecturi: https://0018-223-178-84-123.ngrok-free.app/callback/instagram
    scope: instagram_basic

  facebook:
    clientid: 1697823837436999
    clientsecret: 9d85d01d76e12b0cf00b3e0744051bb9
    redirecturi: https://localhost:3000/callback/facebook
    scope: public_profile,email,pages_manage_engagement,pages_manage_posts,pages_read_engagement,pages_show_list
  youtube:
    clientid: 299988844798-mjiqugl8458o2qgqaao12cth3b31r0cr.apps.googleusercontent.com
    clientsecret: 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
    redirecturi: http://localhost:3000/callback/youtube
    scope: https://www.googleapis.com/auth/youtube https://www.googleapis.com/auth/youtube.readonly https://www.googleapis.com/auth/youtubepartner https://www.googleapis.com/auth/yt-analytics-monetary.readonly https://www.googleapis.com/auth/yt-analytics.readonly








