spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect  # Use MySQL8Dialect for MySQL 8+
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/socialeaze
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver  # Fixed the driver class name
    hikari:
      maximum-pool-size: 5
  application:
    name: api
app:
  cors:
    allowedOrigins: r"https://.+\.stackblitz\.io"
channel:
  linkedin:
    clientid: 86gu36q9t2wcg1
    clientsecret: WPL_AP1.jsYQG4hqKtMvQHKb.EmxZug==
    redirecturi: http://localhost:3000/callback/linkedin
    scope: openid,w_member_social,profile,email
  twitter:
    clientid: RlF6OWxxSXNmQ2RJRjczYndwNkY6MTpjaQ
    clientsecret: xu_7MZm41No0CrddMr0905Jh6hlFdC-P1-PnUWfVl6UHxk48Xl
    redirecturi: http://localhost:3000/callback/twitter
    scope: tweet.read tweet.write offline.access users.read
  Instagram:
    clientid: 813313314325603
    clientsecret: 60473b923df2485fcf55230cf8fe5500
    redirecturi: http://localhost:3000/callback/Instagram
    scope: user_profile,user_media
  facebook:
    clientid: 1401537927905375
    clientsecret: 1649bdcf071ce240491710f0b24f9abc
    redirecturi: http://localhost:3000/callback/facebook
    scope: public_profile,email




