spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect  # Use MySQL8Dialect for MySQL 8+
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/socialeaze
    username: root
    password: Horton_28
    driver-class-name: com.mysql.cj.jdbc.Driver  # Fixed the driver class name
    hikari:
      maximum-pool-size: 5
  application:
    name: api
app:
  cors:
    allowedOrigins: r"https://.+\.stackblitz\.io"
channel:
  linkedin:
    clientid: 862xieml7269ok
    clientsecret: WPL_AP1.hqSjtorV2a6U1kbs.r18kJw==
    redirecturi: http://localhost:3000/callback/linkedin
    scope: openid,w_member_social,profile,email
  twitter:
    clientid: RlF6OWxxSXNmQ2RJRjczYndwNkY6MTpjaQ
    clientsecret: xu_7MZm41No0CrddMr0905Jh6hlFdC-P1-PnUWfVl6UHxk48Xl
    redirecturi: http://localhost:3000/callback/twitter
    scope: tweet.read tweet.write offline.access users.read



